# Generated by Django 4.2.5 on 2024-08-12 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+' with 9 digit OR '0' with 9 digit.", regex='^\\+963\\d{9}$|^09\\d{8}$')]),
        ),
    ]
