# Generated by Django 4.2.5 on 2024-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_last_visit_date_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'doctor'), (2, 'secretary'), (3, 'patient')], default=1),
        ),
    ]
