# Generated by Django 4.2.5 on 2024-08-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='required_tests',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='treatment',
        ),
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='analysis_image',
            field=models.CharField(max_length=1024),
        ),
    ]
