# Generated by Django 4.2.5 on 2024-08-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_address_and_more'),
        ('schedule', '0002_alter_visit_options_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='analysis_image',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient'),
        ),
    ]
