# Generated by Django 4.2.5 on 2024-08-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_address_and_more'),
        ('schedule', '0003_alter_visit_analysis_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient'),
        ),
    ]
